//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.0.0.0
//  Machine:  OSTLT0248323
//  DateTime: 22/03/2016 00:21:58
//  UserName: CFE05
//  GPLEX input file <SpecFiles\BrightScript.lex - 22/03/2016 00:21:50>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: Target machine default
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define BABEL
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using BrightScriptTools.GPlex;
using System.Collections;
using BrightScriptTools.GPlex.Parser;

namespace BrightScriptTools.Compiler
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     public abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     public sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     public sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 206;
        const int initial = 207;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {207, 0};

#region CompressedCharacterMap
    //
    // There are 44 equivalence classes
    // There are 4 character sequence regions
    // There are 2 tables, 172 entries
    // There are 2 runs, 0 singletons
    // Decision tree depth is 2
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 
/*   '\x10' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x20' */ 2, 2, 34, 2, 2, 2, 2, 1, 25, 26, 18, 2, 21, 2, 16, 22, 
/*      '0' */ 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 2, 17, 19, 2, 20, 2, 
/*      '@' */ 2, 14, 5, 8, 13, 12, 6, 30, 39, 10, 33, 43, 32, 35, 7, 11, 
/*      'P' */ 36, 41, 29, 3, 9, 4, 31, 40, 37, 38, 43, 23, 2, 24, 2, 43, 
/*      '`' */ 2, 14, 5, 8, 13, 12, 6, 30, 39, 10, 33, 43, 32, 35, 7, 11, 
/*      'p' */ 36, 41, 29, 3, 9, 4, 31, 40, 37, 38, 43, 27, 15, 28 };
    static sbyte[] mapC2 = new sbyte[46] {
/* '\u01C5' */ 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/* '\u01D5' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/* '\u01E5' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 453) // '\0' <= code <= '\u01C4'
        if (code < 126) // '\0' <= code <= '}'
          return mapC0[code - 0];
        else // '~' <= code <= '\u01C4'
          return (sbyte)2;
      else // '\u01C5' <= code <= '\U0010FFFF'
        if (code < 499) // '\u01C5' <= code <= '\u01F2'
          return mapC2[code - 453];
        else // '\u01F3' <= code <= '\U0010FFFF'
          return (sbyte)2;
    }
#endregion

    static Table[] NxS = new Table[209] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "'"
      new Table(0, 1, 1, new short[] {-1}),
/* NxS[   2] */ // Shortest string "S"
      new Table(29, 30, -1, new short[] {6, 105, 6, 200, 6, -1, 
          6, 6, 6, 6, 6, 6, 68, 6, 6, -1, -1, -1, 6, 198, 6, 6, 
          6, 6, 199, 105, 6, 6, 6, 6}),
/* NxS[   3] */ // Shortest string "U"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 195, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 61, 6, 6, 6, 6, 6, 6}),
/* NxS[   4] */ // Shortest string "B"
      new Table(29, 30, -1, new short[] {188, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 187, 6, 6, 6}),
/* NxS[   5] */ // Shortest string "F"
      new Table(29, 30, -1, new short[] {6, 6, 6, 172, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 169, 6, 6, 
          6, 6, 6, 170, 171, 6, 6, 6}),
/* NxS[   6] */ // Shortest string "N"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[   7] */ // Shortest string "C"
      new Table(29, 30, -1, new short[] {159, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 68, 6, 6, 6, 6, -1, -1, -1, 156, 6, 6, 6, 
          6, 6, 6, 6, 157, 6, 158, 6}),
/* NxS[   8] */ // Shortest string "T"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 155, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 105}),
/* NxS[   9] */ // Shortest string "I"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          144, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  10] */ // Shortest string "O"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 140, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  11] */ // Shortest string "E"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 138, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          137, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  12] */ // Shortest string "D"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 120, 121, 6, 6}),
/* NxS[  13] */ // Shortest string "A"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 119, 6, 59, 6, 
          6, 6, 105, 6, 6, 6, 6, 6}),
/* NxS[  14] */ new Table(0, 0, -1, null), // Shortest string "|"
/* NxS[  15] */ // Shortest string "."
      new Table(42, 1, -1, new short[] {35}),
/* NxS[  16] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[  17] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[  18] */ new Table(0, 0, -1, null), // Shortest string "<"
/* NxS[  19] */ new Table(0, 0, -1, null), // Shortest string ">"
/* NxS[  20] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  21] */ new Table(0, 0, -1, null), // Shortest string "/"
/* NxS[  22] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[  23] */ new Table(0, 0, -1, null), // Shortest string "]"
/* NxS[  24] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[  25] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[  26] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  27] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  28] */ // Shortest string "R"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 105, 6, 6, 
          51, 6, 6, 106, 6, 107, 6, 6}),
/* NxS[  29] */ // Shortest string "G"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 74, 6, 6}),
/* NxS[  30] */ // Shortest string "V"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 70, 6, 6, 71}),
/* NxS[  31] */ // Shortest string "L"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 61, 6, 62, 63, 64, 6, 6}),
/* NxS[  32] */ // Shortest string "M"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 51, 6, 6, 6, 52}),
/* NxS[  33] */ // Shortest string "W"
      new Table(29, 30, -1, new short[] {37, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 36}),
/* NxS[  34] */ // Shortest string "0"
      new Table(42, 19, -1, new short[] {34, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 35}),
/* NxS[  35] */ // Shortest string ".0"
      new Table(42, 1, -1, new short[] {35}),
/* NxS[  36] */ // Shortest string "WA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 50, 6, 6, 6, 6}),
/* NxS[  37] */ // Shortest string "WR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 38, 6, 6, 6, 6}),
/* NxS[  38] */ // Shortest string "WRI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 39, 6, 6, 6, 6, 6}),
/* NxS[  39] */ // Shortest string "WRIT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 40, 6, 6}),
/* NxS[  40] */ // Shortest string "READ"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 41}),
/* NxS[  41] */ // Shortest string "READA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 42, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  42] */ // Shortest string "READAS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 43, 6, 6, 6, 6, 6, 6}),
/* NxS[  43] */ // Shortest string "READASC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 44, 6, 6, 6, 6}),
/* NxS[  44] */ // Shortest string "READASCI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 45, 6, 6, 6, 6}),
/* NxS[  45] */ // Shortest string "COPY"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 46, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  46] */ // Shortest string "COPYF"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 47, 6, 6, 6, 6}),
/* NxS[  47] */ // Shortest string "COPYFI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 48, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  48] */ // Shortest string "TYP"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 49, 6, 6}),
/* NxS[  49] */ // Shortest string "SIN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  50] */ // Shortest string "LEF"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 49, 6, 6, 6, 6, 6}),
/* NxS[  51] */ // Shortest string "RN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 49, 6}),
/* NxS[  52] */ // Shortest string "MA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 53, 6, 6, 6, 6, 6}),
/* NxS[  53] */ // Shortest string "MAT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 54, 6, 6, 6, 6, 6, 6}),
/* NxS[  54] */ // Shortest string "MATC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 55, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  55] */ // Shortest string "MATCH"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 56, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  56] */ // Shortest string "MATCHF"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 57, 6, 6, 6, 6}),
/* NxS[  57] */ // Shortest string "MATCHFI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 58, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  58] */ // Shortest string "MATCHFIL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 59, 6, 6}),
/* NxS[  59] */ // Shortest string "AB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 49, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  60] */ // Shortest string "\"\""
      new Table(34, 11, 208, new short[] {60, 208, 208, 208, 208, 208, 
          208, 208, 208, 208, -1}),
/* NxS[  61] */ // Shortest string "UC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 69}),
/* NxS[  62] */ // Shortest string "LI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 65, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  63] */ // Shortest string "LO"
      new Table(29, 30, -1, new short[] {6, 49, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  64] */ // Shortest string "LE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 50, 
          49, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  65] */ // Shortest string "LIS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 66, 6, 6, 6, 6, 6}),
/* NxS[  66] */ // Shortest string "LIST"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 67, 6}),
/* NxS[  67] */ // Shortest string "LISTD"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 68, 6, 6, 6, 6}),
/* NxS[  68] */ // Shortest string "SQ"
      new Table(29, 30, -1, new short[] {49, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  69] */ // Shortest string "UCA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 48, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  70] */ // Shortest string "VO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 72, 6, 6, 6, 6}),
/* NxS[  71] */ // Shortest string "VA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 49, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  72] */ // Shortest string "VOI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 73, 6}),
/* NxS[  73] */ // Shortest string "VOID"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  74] */ // Shortest string "GE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 75, 6, 6, 6, 6, 6}),
/* NxS[  75] */ // Shortest string "GET"
      new Table(29, 30, -1, new short[] {6, 6, 6, 77, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 76, 6, 6, 6, 6}),
/* NxS[  76] */ // Shortest string "GETI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          99, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  77] */ // Shortest string "GETL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 78}),
/* NxS[  78] */ // Shortest string "GETLA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 79, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  79] */ // Shortest string "GETLAS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 80, 6, 6, 6, 6, 6}),
/* NxS[  80] */ // Shortest string "GETLAST"
      new Table(29, 30, -1, new short[] {81, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  81] */ // Shortest string "GETLASTR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 82, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  82] */ // Shortest string "GETLASTRU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          83, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  83] */ // Shortest string "GETLASTRUN"
      new Table(29, 30, -1, new short[] {85, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 84, 6, 6, 6, 6, 6, 6}),
/* NxS[  84] */ // Shortest string "GETLASTRUNC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 95, 6, 6, 6}),
/* NxS[  85] */ // Shortest string "GETLASTRUNR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 86, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  86] */ // Shortest string "GETLASTRUNRU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          87, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  87] */ // Shortest string "GETLASTRUNRUN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 88, 6, 6, 6, 6, 6}),
/* NxS[  88] */ // Shortest string "GETLASTRUNRUNT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 89, 6, 6, 6, 6}),
/* NxS[  89] */ // Shortest string "GETLASTRUNRUNTI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          90, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  90] */ // Shortest string "GETLASTRUNCOMPIL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 91, 6, 6}),
/* NxS[  91] */ // Shortest string "GETLASTRUNCOMPILE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 92, 6, 6}),
/* NxS[  92] */ // Shortest string "GETLASTRUNCOMPILEE"
      new Table(29, 30, -1, new short[] {93, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  93] */ // Shortest string "GETLASTRUNCOMPILEER"
      new Table(29, 30, -1, new short[] {94, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  94] */ // Shortest string "GETLASTRUNCOMPILEERR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 68, 6, 6, 6}),
/* NxS[  95] */ // Shortest string "GETLASTRUNCO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          96, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  96] */ // Shortest string "GETLASTRUNCOM"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 97, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  97] */ // Shortest string "GETLASTRUNCOMP"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 98, 6, 6, 6, 6}),
/* NxS[  98] */ // Shortest string "GETLASTRUNCOMPI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 90, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[  99] */ // Shortest string "GETIN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 100, 6, 6, 6, 6, 6}),
/* NxS[ 100] */ // Shortest string "GETINT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 101, 6, 6}),
/* NxS[ 101] */ // Shortest string "GETINTE"
      new Table(29, 30, -1, new short[] {102, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 102] */ // Shortest string "GETINTER"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 103, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 103] */ // Shortest string "GETINTERF"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 104}),
/* NxS[ 104] */ // Shortest string "GETINTERFA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 48, 6, 6, 6, 6, 6, 6}),
/* NxS[ 105] */ // Shortest string "SI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          49, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 106] */ // Shortest string "RI"
      new Table(29, 30, -1, new short[] {6, 118, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 107] */ // Shortest string "RE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 108, 6, 
          6, 6, 6, 6, 6, 6, 6, 109}),
/* NxS[ 108] */ // Shortest string "REB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 110, 6, 6, 6}),
/* NxS[ 109] */ // Shortest string "REA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 40, 6}),
/* NxS[ 110] */ // Shortest string "REBO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 111, 6, 6, 6}),
/* NxS[ 111] */ // Shortest string "REBOO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 112, 6, 6, 6, 6, 6}),
/* NxS[ 112] */ // Shortest string "REBOOT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 113, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 113] */ // Shortest string "REBOOTS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 114, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 114] */ // Shortest string "REBOOTSY"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 115, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 115] */ // Shortest string "REBOOTSYS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 116, 6, 6, 6, 6, 6}),
/* NxS[ 116] */ // Shortest string "REBOOTSYST"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 117, 6, 6}),
/* NxS[ 117] */ // Shortest string "REBOOTSYSTE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          49, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 118] */ // Shortest string "RIG"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 50, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 119] */ // Shortest string "AS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 49, 6, 6, 6, 6, 6, 6}),
/* NxS[ 120] */ // Shortest string "DO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 134, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 121] */ // Shortest string "DE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 122, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 122] */ // Shortest string "DEL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 123, 6, 6}),
/* NxS[ 123] */ // Shortest string "DELE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 124, 6, 6, 6, 6, 6}),
/* NxS[ 124] */ // Shortest string "DELET"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 125, 6, 6}),
/* NxS[ 125] */ // Shortest string "DELETE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 46, 
          6, 6, 6, 6, 6, 6, 126, 6}),
/* NxS[ 126] */ // Shortest string "CREATED"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 127, 6, 6, 6, 6}),
/* NxS[ 127] */ // Shortest string "CREATEDI"
      new Table(29, 30, -1, new short[] {128, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 128] */ // Shortest string "CREATEDIR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 129, 6, 6}),
/* NxS[ 129] */ // Shortest string "CREATEDIRE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 130, 6, 6, 6, 6, 6, 6}),
/* NxS[ 130] */ // Shortest string "CREATEDIREC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 131, 6, 6, 6, 6, 6}),
/* NxS[ 131] */ // Shortest string "CREATEDIRECT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 132, 6, 6, 6}),
/* NxS[ 132] */ // Shortest string "CREATEDIRECTO"
      new Table(29, 30, -1, new short[] {133, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 133] */ // Shortest string "CREATEDIRECTOR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 49, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 134] */ // Shortest string "DOU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 135, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 135] */ // Shortest string "DOUB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 136, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 136] */ // Shortest string "DOUBL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 73, 6, 6}),
/* NxS[ 137] */ // Shortest string "EN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 139, 6}),
/* NxS[ 138] */ // Shortest string "EX"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 49, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 139] */ // Shortest string "END"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 140] */ // Shortest string "OB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 141, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 141] */ // Shortest string "OBJ"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 142, 6, 6}),
/* NxS[ 142] */ // Shortest string "OBJE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 143, 6, 6, 6, 6, 6, 6}),
/* NxS[ 143] */ // Shortest string "FLOA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 73, 6, 6, 6, 6, 6}),
/* NxS[ 144] */ // Shortest string "IN"
      new Table(29, 30, -1, new short[] {6, 6, 147, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 145, 6, 6, 6, 
          6, 6, 146, 6, 6, 6, 6, 6}),
/* NxS[ 145] */ // Shortest string "INS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 68, 6, 6, 6, 6, 6}),
/* NxS[ 146] */ // Shortest string "INT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 149, 6, 6}),
/* NxS[ 147] */ // Shortest string "INV"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 148}),
/* NxS[ 148] */ // Shortest string "INVA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 70, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 149] */ // Shortest string "INTE"
      new Table(29, 30, -1, new short[] {150, 151, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 150] */ // Shortest string "INTER"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 153, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 151] */ // Shortest string "INTEG"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 152, 6, 6}),
/* NxS[ 152] */ // Shortest string "INTEGE"
      new Table(29, 30, -1, new short[] {73, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 153] */ // Shortest string "INTERF"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 154}),
/* NxS[ 154] */ // Shortest string "INTERFA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 136, 6, 6, 6, 6, 6, 6}),
/* NxS[ 155] */ // Shortest string "TY"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 48, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 156] */ // Shortest string "CS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          63, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 157] */ // Shortest string "CO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 168, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 49, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 158] */ // Shortest string "CD"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 71, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 159] */ // Shortest string "CR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 160, 6, 6}),
/* NxS[ 160] */ // Shortest string "CRE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 161}),
/* NxS[ 161] */ // Shortest string "CREA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 162, 6, 6, 6, 6, 6}),
/* NxS[ 162] */ // Shortest string "CREAT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 163, 6, 6}),
/* NxS[ 163] */ // Shortest string "CREATE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 164, 6, 126, 6}),
/* NxS[ 164] */ // Shortest string "CREATEO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 165, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 165] */ // Shortest string "CREATEOB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 166, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 166] */ // Shortest string "CREATEOBJ"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 167, 6, 6}),
/* NxS[ 167] */ // Shortest string "CREATEOBJE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 50, 6, 6, 6, 6, 6, 6}),
/* NxS[ 168] */ // Shortest string "COP"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 45, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 169] */ // Shortest string "FU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          181, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 170] */ // Shortest string "FI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 49, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 171] */ // Shortest string "FO"
      new Table(29, 30, -1, new short[] {174, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 172] */ // Shortest string "FL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 173, 6, 6, 6}),
/* NxS[ 173] */ // Shortest string "FLO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 143}),
/* NxS[ 174] */ // Shortest string "FOR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          175, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 175] */ // Shortest string "FORM"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 176}),
/* NxS[ 176] */ // Shortest string "FORMA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 177, 6, 6, 6, 6, 6}),
/* NxS[ 177] */ // Shortest string "FORMAT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 178, 6}),
/* NxS[ 178] */ // Shortest string "FORMATD"
      new Table(29, 30, -1, new short[] {179, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 179] */ // Shortest string "FORMATDR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 180, 6, 6, 6, 6}),
/* NxS[ 180] */ // Shortest string "FORMATDRI"
      new Table(29, 30, -1, new short[] {6, 6, 48, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 181] */ // Shortest string "FUN"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 182, 6, 6, 6, 6, 6, 6}),
/* NxS[ 182] */ // Shortest string "FUNC"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 183, 6, 6, 6, 6, 6}),
/* NxS[ 183] */ // Shortest string "FUNCT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 184, 6, 6, 6, 6}),
/* NxS[ 184] */ // Shortest string "FUNCTI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 185, 6, 6, 6}),
/* NxS[ 185] */ // Shortest string "FUNCTIO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          186, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 186] */ // Shortest string "FUNCTION"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 187] */ // Shortest string "BO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 49, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 191, 6, 6, 6}),
/* NxS[ 188] */ // Shortest string "BR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 189, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 189] */ // Shortest string "BRS"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 190, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 190] */ // Shortest string "BRSU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 73, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 191] */ // Shortest string "BOO"
      new Table(29, 30, -1, new short[] {6, 6, 6, 192, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 192] */ // Shortest string "BOOL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 193, 6, 6}),
/* NxS[ 193] */ // Shortest string "BOOLE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 194}),
/* NxS[ 194] */ // Shortest string "BOOLEA"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          73, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 195] */ // Shortest string "UP"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 196, 6, 6, 6, 6, 6}),
/* NxS[ 196] */ // Shortest string "UPT"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 197, 6, 6, 6, 6}),
/* NxS[ 197] */ // Shortest string "UPTI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          48, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 198] */ // Shortest string "SU"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 206, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 199] */ // Shortest string "ST"
      new Table(29, 30, -1, new short[] {202, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 200] */ // Shortest string "SL"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 201, 6, 6}),
/* NxS[ 201] */ // Shortest string "SLE"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 138, 6, 6}),
/* NxS[ 202] */ // Shortest string "STR"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 203, 6, 6, 6, 6}),
/* NxS[ 203] */ // Shortest string "STRI"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          204, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 204] */ // Shortest string "STRIN"
      new Table(29, 30, -1, new short[] {6, 205, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 205] */ // Shortest string "STRING"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 49, 6, 6, 6, 6}),
/* NxS[ 206] */ // Shortest string "SUB"
      new Table(29, 30, -1, new short[] {6, 6, 6, 6, 6, -1, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, -1, 6, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6}),
/* NxS[ 207] */ // Shortest string ""
      new Table(40, 40, 6, new short[] {33, 6, 34, 6, -1, 1, 
          -1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
          17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 6, 
          208, 32}),
/* NxS[ 208] */ // Shortest string "\""
      new Table(34, 11, 208, new short[] {60, 208, 208, 208, 208, 208, 
          208, 208, 208, 208, -1}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 44;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     public Scanner(Stream file) {
            SetSource(file, 0); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     public Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1: // Recognized '{Cmnt}',	Shortest string "'"
return (int)Tokens.bsCmnt;
            break;
        case 2: // Recognized '{Ident}',	Shortest string "S"
        case 3: // Recognized '{Ident}',	Shortest string "U"
        case 4: // Recognized '{Ident}',	Shortest string "B"
        case 5: // Recognized '{Ident}',	Shortest string "F"
        case 6: // Recognized '{Ident}',	Shortest string "N"
        case 7: // Recognized '{Ident}',	Shortest string "C"
        case 8: // Recognized '{Ident}',	Shortest string "T"
        case 9: // Recognized '{Ident}',	Shortest string "I"
        case 10: // Recognized '{Ident}',	Shortest string "O"
        case 11: // Recognized '{Ident}',	Shortest string "E"
        case 12: // Recognized '{Ident}',	Shortest string "D"
        case 13: // Recognized '{Ident}',	Shortest string "A"
        case 28: // Recognized '{Ident}',	Shortest string "R"
        case 29: // Recognized '{Ident}',	Shortest string "G"
        case 30: // Recognized '{Ident}',	Shortest string "V"
        case 31: // Recognized '{Ident}',	Shortest string "L"
        case 32: // Recognized '{Ident}',	Shortest string "M"
        case 33: // Recognized '{Ident}',	Shortest string "W"
        case 36: // Recognized '{Ident}',	Shortest string "WA"
        case 37: // Recognized '{Ident}',	Shortest string "WR"
        case 38: // Recognized '{Ident}',	Shortest string "WRI"
        case 39: // Recognized '{Ident}',	Shortest string "WRIT"
        case 40: // Recognized '{Ident}',	Shortest string "READ"
        case 41: // Recognized '{Ident}',	Shortest string "READA"
        case 42: // Recognized '{Ident}',	Shortest string "READAS"
        case 43: // Recognized '{Ident}',	Shortest string "READASC"
        case 44: // Recognized '{Ident}',	Shortest string "READASCI"
        case 45: // Recognized '{Ident}',	Shortest string "COPY"
        case 46: // Recognized '{Ident}',	Shortest string "COPYF"
        case 47: // Recognized '{Ident}',	Shortest string "COPYFI"
        case 48: // Recognized '{Ident}',	Shortest string "TYP"
        case 50: // Recognized '{Ident}',	Shortest string "LEF"
        case 51: // Recognized '{Ident}',	Shortest string "RN"
        case 52: // Recognized '{Ident}',	Shortest string "MA"
        case 53: // Recognized '{Ident}',	Shortest string "MAT"
        case 54: // Recognized '{Ident}',	Shortest string "MATC"
        case 55: // Recognized '{Ident}',	Shortest string "MATCH"
        case 56: // Recognized '{Ident}',	Shortest string "MATCHF"
        case 57: // Recognized '{Ident}',	Shortest string "MATCHFI"
        case 58: // Recognized '{Ident}',	Shortest string "MATCHFIL"
        case 59: // Recognized '{Ident}',	Shortest string "AB"
        case 61: // Recognized '{Ident}',	Shortest string "UC"
        case 62: // Recognized '{Ident}',	Shortest string "LI"
        case 63: // Recognized '{Ident}',	Shortest string "LO"
        case 64: // Recognized '{Ident}',	Shortest string "LE"
        case 65: // Recognized '{Ident}',	Shortest string "LIS"
        case 66: // Recognized '{Ident}',	Shortest string "LIST"
        case 67: // Recognized '{Ident}',	Shortest string "LISTD"
        case 68: // Recognized '{Ident}',	Shortest string "SQ"
        case 69: // Recognized '{Ident}',	Shortest string "UCA"
        case 70: // Recognized '{Ident}',	Shortest string "VO"
        case 71: // Recognized '{Ident}',	Shortest string "VA"
        case 72: // Recognized '{Ident}',	Shortest string "VOI"
        case 74: // Recognized '{Ident}',	Shortest string "GE"
        case 75: // Recognized '{Ident}',	Shortest string "GET"
        case 76: // Recognized '{Ident}',	Shortest string "GETI"
        case 77: // Recognized '{Ident}',	Shortest string "GETL"
        case 78: // Recognized '{Ident}',	Shortest string "GETLA"
        case 79: // Recognized '{Ident}',	Shortest string "GETLAS"
        case 80: // Recognized '{Ident}',	Shortest string "GETLAST"
        case 81: // Recognized '{Ident}',	Shortest string "GETLASTR"
        case 82: // Recognized '{Ident}',	Shortest string "GETLASTRU"
        case 83: // Recognized '{Ident}',	Shortest string "GETLASTRUN"
        case 84: // Recognized '{Ident}',	Shortest string "GETLASTRUNC"
        case 85: // Recognized '{Ident}',	Shortest string "GETLASTRUNR"
        case 86: // Recognized '{Ident}',	Shortest string "GETLASTRUNRU"
        case 87: // Recognized '{Ident}',	Shortest string "GETLASTRUNRUN"
        case 88: // Recognized '{Ident}',	Shortest string "GETLASTRUNRUNT"
        case 89: // Recognized '{Ident}',	Shortest string "GETLASTRUNRUNTI"
        case 90: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPIL"
        case 91: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPILE"
        case 92: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPILEE"
        case 93: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPILEER"
        case 94: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPILEERR"
        case 95: // Recognized '{Ident}',	Shortest string "GETLASTRUNCO"
        case 96: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOM"
        case 97: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMP"
        case 98: // Recognized '{Ident}',	Shortest string "GETLASTRUNCOMPI"
        case 99: // Recognized '{Ident}',	Shortest string "GETIN"
        case 100: // Recognized '{Ident}',	Shortest string "GETINT"
        case 101: // Recognized '{Ident}',	Shortest string "GETINTE"
        case 102: // Recognized '{Ident}',	Shortest string "GETINTER"
        case 103: // Recognized '{Ident}',	Shortest string "GETINTERF"
        case 104: // Recognized '{Ident}',	Shortest string "GETINTERFA"
        case 105: // Recognized '{Ident}',	Shortest string "SI"
        case 106: // Recognized '{Ident}',	Shortest string "RI"
        case 107: // Recognized '{Ident}',	Shortest string "RE"
        case 108: // Recognized '{Ident}',	Shortest string "REB"
        case 109: // Recognized '{Ident}',	Shortest string "REA"
        case 110: // Recognized '{Ident}',	Shortest string "REBO"
        case 111: // Recognized '{Ident}',	Shortest string "REBOO"
        case 112: // Recognized '{Ident}',	Shortest string "REBOOT"
        case 113: // Recognized '{Ident}',	Shortest string "REBOOTS"
        case 114: // Recognized '{Ident}',	Shortest string "REBOOTSY"
        case 115: // Recognized '{Ident}',	Shortest string "REBOOTSYS"
        case 116: // Recognized '{Ident}',	Shortest string "REBOOTSYST"
        case 117: // Recognized '{Ident}',	Shortest string "REBOOTSYSTE"
        case 118: // Recognized '{Ident}',	Shortest string "RIG"
        case 120: // Recognized '{Ident}',	Shortest string "DO"
        case 121: // Recognized '{Ident}',	Shortest string "DE"
        case 122: // Recognized '{Ident}',	Shortest string "DEL"
        case 123: // Recognized '{Ident}',	Shortest string "DELE"
        case 124: // Recognized '{Ident}',	Shortest string "DELET"
        case 125: // Recognized '{Ident}',	Shortest string "DELETE"
        case 126: // Recognized '{Ident}',	Shortest string "CREATED"
        case 127: // Recognized '{Ident}',	Shortest string "CREATEDI"
        case 128: // Recognized '{Ident}',	Shortest string "CREATEDIR"
        case 129: // Recognized '{Ident}',	Shortest string "CREATEDIRE"
        case 130: // Recognized '{Ident}',	Shortest string "CREATEDIREC"
        case 131: // Recognized '{Ident}',	Shortest string "CREATEDIRECT"
        case 132: // Recognized '{Ident}',	Shortest string "CREATEDIRECTO"
        case 133: // Recognized '{Ident}',	Shortest string "CREATEDIRECTOR"
        case 134: // Recognized '{Ident}',	Shortest string "DOU"
        case 135: // Recognized '{Ident}',	Shortest string "DOUB"
        case 136: // Recognized '{Ident}',	Shortest string "DOUBL"
        case 137: // Recognized '{Ident}',	Shortest string "EN"
        case 138: // Recognized '{Ident}',	Shortest string "EX"
        case 140: // Recognized '{Ident}',	Shortest string "OB"
        case 141: // Recognized '{Ident}',	Shortest string "OBJ"
        case 142: // Recognized '{Ident}',	Shortest string "OBJE"
        case 143: // Recognized '{Ident}',	Shortest string "FLOA"
        case 144: // Recognized '{Ident}',	Shortest string "IN"
        case 145: // Recognized '{Ident}',	Shortest string "INS"
        case 147: // Recognized '{Ident}',	Shortest string "INV"
        case 148: // Recognized '{Ident}',	Shortest string "INVA"
        case 149: // Recognized '{Ident}',	Shortest string "INTE"
        case 150: // Recognized '{Ident}',	Shortest string "INTER"
        case 151: // Recognized '{Ident}',	Shortest string "INTEG"
        case 152: // Recognized '{Ident}',	Shortest string "INTEGE"
        case 153: // Recognized '{Ident}',	Shortest string "INTERF"
        case 154: // Recognized '{Ident}',	Shortest string "INTERFA"
        case 155: // Recognized '{Ident}',	Shortest string "TY"
        case 156: // Recognized '{Ident}',	Shortest string "CS"
        case 157: // Recognized '{Ident}',	Shortest string "CO"
        case 158: // Recognized '{Ident}',	Shortest string "CD"
        case 159: // Recognized '{Ident}',	Shortest string "CR"
        case 160: // Recognized '{Ident}',	Shortest string "CRE"
        case 161: // Recognized '{Ident}',	Shortest string "CREA"
        case 162: // Recognized '{Ident}',	Shortest string "CREAT"
        case 163: // Recognized '{Ident}',	Shortest string "CREATE"
        case 164: // Recognized '{Ident}',	Shortest string "CREATEO"
        case 165: // Recognized '{Ident}',	Shortest string "CREATEOB"
        case 166: // Recognized '{Ident}',	Shortest string "CREATEOBJ"
        case 167: // Recognized '{Ident}',	Shortest string "CREATEOBJE"
        case 168: // Recognized '{Ident}',	Shortest string "COP"
        case 169: // Recognized '{Ident}',	Shortest string "FU"
        case 170: // Recognized '{Ident}',	Shortest string "FI"
        case 171: // Recognized '{Ident}',	Shortest string "FO"
        case 172: // Recognized '{Ident}',	Shortest string "FL"
        case 173: // Recognized '{Ident}',	Shortest string "FLO"
        case 174: // Recognized '{Ident}',	Shortest string "FOR"
        case 175: // Recognized '{Ident}',	Shortest string "FORM"
        case 176: // Recognized '{Ident}',	Shortest string "FORMA"
        case 177: // Recognized '{Ident}',	Shortest string "FORMAT"
        case 178: // Recognized '{Ident}',	Shortest string "FORMATD"
        case 179: // Recognized '{Ident}',	Shortest string "FORMATDR"
        case 180: // Recognized '{Ident}',	Shortest string "FORMATDRI"
        case 181: // Recognized '{Ident}',	Shortest string "FUN"
        case 182: // Recognized '{Ident}',	Shortest string "FUNC"
        case 183: // Recognized '{Ident}',	Shortest string "FUNCT"
        case 184: // Recognized '{Ident}',	Shortest string "FUNCTI"
        case 185: // Recognized '{Ident}',	Shortest string "FUNCTIO"
        case 187: // Recognized '{Ident}',	Shortest string "BO"
        case 188: // Recognized '{Ident}',	Shortest string "BR"
        case 189: // Recognized '{Ident}',	Shortest string "BRS"
        case 190: // Recognized '{Ident}',	Shortest string "BRSU"
        case 191: // Recognized '{Ident}',	Shortest string "BOO"
        case 192: // Recognized '{Ident}',	Shortest string "BOOL"
        case 193: // Recognized '{Ident}',	Shortest string "BOOLE"
        case 194: // Recognized '{Ident}',	Shortest string "BOOLEA"
        case 195: // Recognized '{Ident}',	Shortest string "UP"
        case 196: // Recognized '{Ident}',	Shortest string "UPT"
        case 197: // Recognized '{Ident}',	Shortest string "UPTI"
        case 198: // Recognized '{Ident}',	Shortest string "SU"
        case 199: // Recognized '{Ident}',	Shortest string "ST"
        case 200: // Recognized '{Ident}',	Shortest string "SL"
        case 201: // Recognized '{Ident}',	Shortest string "SLE"
        case 204: // Recognized '{Ident}',	Shortest string "STRIN"
return (int)Tokens.bsIdent;
            break;
        case 14: // Recognized '{bar}',	Shortest string "|"
return (int)Tokens.bar;
            break;
        case 15: // Recognized '{dot}',	Shortest string "."
return (int)Tokens.dot;
            break;
        case 16: // Recognized '{semi}',	Shortest string ";"
return (int)Tokens.semi;
            break;
        case 17: // Recognized '{star}',	Shortest string "*"
return (int)Tokens.star;
            break;
        case 18: // Recognized '{lt}',	Shortest string "<"
return (int)Tokens.lt;
            break;
        case 19: // Recognized '{gt}',	Shortest string ">"
return (int)Tokens.gt;
            break;
        case 20: // Recognized '{comma}',	Shortest string ","
return (int)Tokens.comma;
            break;
        case 21: // Recognized '{slash}',	Shortest string "/"
return (int)Tokens.slash;
            break;
        case 22: // Recognized '{lBrac}',	Shortest string "["
return (int)Tokens.lBrac;
            break;
        case 23: // Recognized '{rBrac}',	Shortest string "]"
return (int)Tokens.rBrac;
            break;
        case 24: // Recognized '{lPar}',	Shortest string "("
return (int)Tokens.lPar;
            break;
        case 25: // Recognized '{rPar}',	Shortest string ")"
return (int)Tokens.rPar;
            break;
        case 26: // Recognized '{lBrace}',	Shortest string "{"
return (int)Tokens.lBrace;
            break;
        case 27: // Recognized '{rBrace}',	Shortest string "}"
return (int)Tokens.rBrace;
            break;
        case 34: // Recognized '{Number}',	Shortest string "0"
        case 35: // Recognized '{Number}',	Shortest string ".0"
return (int)Tokens.bsNumber;
            break;
        case 49: // Recognized '{Funcs}',	Shortest string "SIN"
        case 146: // Recognized '{Funcs}',	Shortest string "INT"
        case 202: // Recognized '{Funcs}',	Shortest string "STR"
        case 203: // Recognized '{Funcs}',	Shortest string "STRI"
return (int)Tokens.bsFuncs;
            break;
        case 60: // Recognized '{Str}',	Shortest string "\"\""
return (int)Tokens.bsStr;
            break;
        case 73: // Recognized '{Typs}',	Shortest string "VOID"
        case 205: // Recognized '{Typs}',	Shortest string "STRING"
return (int)Tokens.bsType;
            break;
        case 119: // Recognized 'AS',	Shortest string "AS"
return (int)Tokens.bsAs;
            break;
        case 139: // Recognized 'END',	Shortest string "END"
return (int)Tokens.bsEnd;
            break;
        case 186: // Recognized 'FUNCTION',	Shortest string "FUNCTION"
return (int)Tokens.bsFunction;
            break;
        case 206: // Recognized 'SUB',	Shortest string "SUB"
return (int)Tokens.bsSub;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
