//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.0.0.0
//  Machine:  OSTLT0248323
//  DateTime: 21/06/2016 16:02:35
//  UserName: CFE05
//  GPLEX input file <SpecFiles\Debugger.lex - 21/06/2016 16:02:20>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: Target machine default
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define BABEL
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using BrightScriptTools.GPlex;
using System.Collections;
using BrightScriptTools.GPlex.Parser;

namespace BrightScriptDebug.Compiler
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     public abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     public sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     public sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 111;
        const int initial = 112;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {112, 0};

#region CompressedCharacterMap
    //
    // There are 39 equivalence classes
    // There are 4 character sequence regions
    // There are 2 tables, 172 entries
    // There are 2 runs, 0 singletons
    // Decision tree depth is 2
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 12, 38, 38, 11, 38, 38, 
/*   '\x10' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 
/*   '\x20' */ 38, 38, 38, 38, 38, 38, 38, 37, 7, 8, 3, 38, 5, 14, 1, 6, 
/*      '0' */ 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 2, 38, 38, 13, 4, 38, 
/*      '@' */ 38, 31, 25, 24, 28, 29, 22, 26, 27, 17, 36, 33, 30, 34, 18, 21, 
/*      'P' */ 15, 36, 16, 20, 19, 23, 32, 36, 36, 36, 36, 38, 38, 38, 38, 36, 
/*      '`' */ 38, 31, 25, 24, 28, 29, 22, 26, 27, 17, 36, 33, 30, 34, 18, 21, 
/*      'p' */ 15, 36, 16, 20, 19, 23, 32, 36, 36, 36, 36, 9, 38, 10 };
    static sbyte[] mapC2 = new sbyte[46] {
/* '\u01C5' */ 0, 38, 38, 0, 38, 38, 0, 38, 38, 38, 38, 38, 38, 38, 38, 38, 
/* '\u01D5' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 
/* '\u01E5' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 0 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 453) // '\0' <= code <= '\u01C4'
        if (code < 126) // '\0' <= code <= '}'
          return mapC0[code - 0];
        else // '~' <= code <= '\u01C4'
          return (sbyte)38;
      else // '\u01C5' <= code <= '\U0010FFFF'
        if (code < 499) // '\u01C5' <= code <= '\u01F2'
          return mapC2[code - 453];
        else // '\u01F3' <= code <= '\U0010FFFF'
          return (sbyte)38;
    }
#endregion

    static Table[] NxS = new Table[118] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "."
      new Table(35, 1, -1, new sbyte[] {28}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string ":"
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string ">"
/* NxS[   5] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[   6] */ new Table(0, 0, -1, null), // Shortest string "/"
/* NxS[   7] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[   8] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[   9] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  11] */ // Shortest string "\r"
      new Table(12, 1, -1, new sbyte[] {12}),
/* NxS[  12] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[  13] */ new Table(0, 0, -1, null), // Shortest string "="
/* NxS[  14] */ // Shortest string "-"
      new Table(14, 1, -1, new sbyte[] {114}),
/* NxS[  15] */ // Shortest string "P"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 107}),
/* NxS[  16] */ // Shortest string "R"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 101, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  17] */ // Shortest string "I"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  18] */ // Shortest string "S"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 98}),
/* NxS[  19] */ // Shortest string "F"
      new Table(15, 22, -1, new sbyte[] {17, 17, 88, 17, 17, 17, 
          17, 17, 89, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  20] */ // Shortest string "C"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          74, 17, 75, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  21] */ // Shortest string "B"
      new Table(15, 22, -1, new sbyte[] {17, 55, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 56, 17, 17, 17, 17, 17}),
/* NxS[  22] */ // Shortest string "D"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 47, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  23] */ // Shortest string "L"
      new Table(15, 22, -1, new sbyte[] {17, 17, 40, 17, 17, 17, 
          41, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  24] */ // Shortest string "V"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 32, 17, 17, 17, 17, 17}),
/* NxS[  25] */ // Shortest string "M"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 29, 17, 17, 17, 17, 17}),
/* NxS[  26] */ // Shortest string "0"
      new Table(35, 6, -1, new sbyte[] {26, -1, -1, -1, -1, 28}),
/* NxS[  27] */ // Shortest string "''"
      new Table(37, 15, 113, new sbyte[] {27, 113, -1, 113, 113, 113, 
          113, 113, 113, 113, 113, 113, 113, -1, -1}),
/* NxS[  28] */ // Shortest string ".0"
      new Table(35, 1, -1, new sbyte[] {28}),
/* NxS[  29] */ // Shortest string "MA"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 30}),
/* NxS[  30] */ // Shortest string "MAI"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 31}),
/* NxS[  31] */ // Shortest string "MAIN"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  32] */ // Shortest string "VA"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 33}),
/* NxS[  33] */ // Shortest string "VAR"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 34}),
/* NxS[  34] */ // Shortest string "VARI"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 35, 17, 17, 17, 17, 17}),
/* NxS[  35] */ // Shortest string "VARIA"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 36, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  36] */ // Shortest string "VARIAB"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 37, 17, 17, 17, 17, 17, 17}),
/* NxS[  37] */ // Shortest string "VARIABL"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 38, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  38] */ // Shortest string "VARIABLE"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 39, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  39] */ // Shortest string "VARIABLES"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  40] */ // Shortest string "LI"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 45}),
/* NxS[  41] */ // Shortest string "LO"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 42, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  42] */ // Shortest string "LOC"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 43, 17, 17, 17, 17, 17}),
/* NxS[  43] */ // Shortest string "LOCA"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 44, 17, 17, 17, 17, 17, 17}),
/* NxS[  44] */ // Shortest string "LOCAL"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  45] */ // Shortest string "LIN"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 46, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  46] */ // Shortest string "LINE"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  47] */ // Shortest string "DE"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 48, 17, 17, 17, 17, 17, 17, 49, 17, 17, 17, 17}),
/* NxS[  48] */ // Shortest string "DEB"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 50, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  49] */ // Shortest string "DEV"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  50] */ // Shortest string "DEBU"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 51, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  51] */ // Shortest string "DEBUG"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 52, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  52] */ // Shortest string "DEBUGG"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 53, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  53] */ // Shortest string "DEBUGGE"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 54}),
/* NxS[  54] */ // Shortest string "DEBUGGER"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  55] */ // Shortest string "BR"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 64}),
/* NxS[  56] */ // Shortest string "BA"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 57, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  57] */ // Shortest string "BAC"
      new Table(33, 21, 17, new sbyte[] {58, 17, 17, 17, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  58] */ // Shortest string "BACK"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 59}),
/* NxS[  59] */ // Shortest string "BACKT"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 60}),
/* NxS[  60] */ // Shortest string "BACKTR"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 61, 17, 17, 17, 17, 17}),
/* NxS[  61] */ // Shortest string "BACKTRA"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 62, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  62] */ // Shortest string "BACKTRAC"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 63, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  63] */ // Shortest string "BACKTRACE"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  64] */ // Shortest string "BRI"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 65, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  65] */ // Shortest string "BRIG"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 66, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  66] */ // Shortest string "BRIGH"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 67}),
/* NxS[  67] */ // Shortest string "BRIGHT"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 68, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  68] */ // Shortest string "BRIGHTS"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 69, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  69] */ // Shortest string "BRIGHTSC"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 70}),
/* NxS[  70] */ // Shortest string "BRIGHTSCR"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 71}),
/* NxS[  71] */ // Shortest string "BRIGHTSCRI"
      new Table(37, 18, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 72}),
/* NxS[  72] */ // Shortest string "BRIGHTSCRIP"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 73}),
/* NxS[  73] */ // Shortest string "BRIGHTSCRIPT"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  74] */ // Shortest string "CO"
      new Table(34, 20, 17, new sbyte[] {81, 17, 17, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  75] */ // Shortest string "CU"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 76}),
/* NxS[  76] */ // Shortest string "CUR"
      new Table(37, 19, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 77}),
/* NxS[  77] */ // Shortest string "CURR"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 78, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  78] */ // Shortest string "CURRE"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 79}),
/* NxS[  79] */ // Shortest string "CURREN"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 80}),
/* NxS[  80] */ // Shortest string "CURRENT"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  81] */ // Shortest string "COM"
      new Table(37, 18, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 82}),
/* NxS[  82] */ // Shortest string "COMP"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 83}),
/* NxS[  83] */ // Shortest string "COMPI"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 84, 17, 17, 17, 17, 17, 17}),
/* NxS[  84] */ // Shortest string "COMPIL"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 85}),
/* NxS[  85] */ // Shortest string "COMPILI"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 86}),
/* NxS[  86] */ // Shortest string "COMPILIN"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 87, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  87] */ // Shortest string "COMPILING"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  88] */ // Shortest string "FI"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 17, 96, 17, 17, 17, 17, 17, 17}),
/* NxS[  89] */ // Shortest string "FU"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 90}),
/* NxS[  90] */ // Shortest string "FUN"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 91, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  91] */ // Shortest string "FUNC"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 92}),
/* NxS[  92] */ // Shortest string "FUNCT"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 93}),
/* NxS[  93] */ // Shortest string "FUNCTI"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          94, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  94] */ // Shortest string "FUNCTIO"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 95}),
/* NxS[  95] */ // Shortest string "FUNCTION"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  96] */ // Shortest string "FIL"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 17, 17, 17, 97, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  97] */ // Shortest string "FILE"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[  98] */ // Shortest string "ST"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          99, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[  99] */ // Shortest string "STO"
      new Table(37, 18, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 100}),
/* NxS[ 100] */ // Shortest string "STOP"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 101] */ // Shortest string "RU"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 102}),
/* NxS[ 102] */ // Shortest string "RUN"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 103}),
/* NxS[ 103] */ // Shortest string "RUNN"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 104}),
/* NxS[ 104] */ // Shortest string "RUNNI"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 105}),
/* NxS[ 105] */ // Shortest string "RUNNIN"
      new Table(15, 22, -1, new sbyte[] {17, 17, 17, 17, 17, 17, 
          17, 17, 17, 17, 17, 106, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17}),
/* NxS[ 106] */ // Shortest string "RUNNING"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 107] */ // Shortest string "PR"
      new Table(37, 20, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 108}),
/* NxS[ 108] */ // Shortest string "PRI"
      new Table(37, 21, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 109}),
/* NxS[ 109] */ // Shortest string "PRIN"
      new Table(37, 22, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, 17, 17, 110}),
/* NxS[ 110] */ // Shortest string "PRINT"
      new Table(37, 17, 17, new sbyte[] {-1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}),
/* NxS[ 111] */ new Table(0, 0, -1, null), // Shortest string "------"
/* NxS[ 112] */ // Shortest string ""
      new Table(20, 36, 17, new sbyte[] {18, 17, 19, 17, 20, 21, 
          17, 17, 22, 17, 23, 17, 24, 17, 25, 26, 17, 113, -1, -1, 1, 2, 
          3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}),
/* NxS[ 113] */ // Shortest string "'"
      new Table(37, 15, 113, new sbyte[] {27, 113, -1, 113, 113, 113, 
          113, 113, 113, 113, 113, 113, 113, -1, -1}),
/* NxS[ 114] */ // Shortest string "--"
      new Table(14, 1, -1, new sbyte[] {115}),
/* NxS[ 115] */ // Shortest string "---"
      new Table(14, 1, -1, new sbyte[] {116}),
/* NxS[ 116] */ // Shortest string "----"
      new Table(14, 1, -1, new sbyte[] {117}),
/* NxS[ 117] */ // Shortest string "-----"
      new Table(14, 1, -1, new sbyte[] {111}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 39;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     public Scanner(Stream file) {
            SetSource(file, 0); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     public Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1: // Recognized '{dot}',	Shortest string "."
return (int)Tokens.dot;
            break;
        case 2: // Recognized '{colon}',	Shortest string ":"
return (int)Tokens.colon;
            break;
        case 3: // Recognized '{star}',	Shortest string "*"
return (int)Tokens.star;
            break;
        case 4: // Recognized '{gt}',	Shortest string ">"
return (int)Tokens.gt;
            break;
        case 5: // Recognized '{comma}',	Shortest string ","
return (int)Tokens.comma;
            break;
        case 6: // Recognized '{slash}',	Shortest string "/"
return (int)Tokens.slash;
            break;
        case 7: // Recognized '{lPar}',	Shortest string "("
return (int)Tokens.lPar;
            break;
        case 8: // Recognized '{rPar}',	Shortest string ")"
return (int)Tokens.rPar;
            break;
        case 9: // Recognized '{lBrace}',	Shortest string "{"
return (int)Tokens.lBrace;
            break;
        case 10: // Recognized '{rBrace}',	Shortest string "}"
return (int)Tokens.rBrace;
            break;
        case 11: // Recognized '{Eol}',	Shortest string "\r"
        case 12: // Recognized '{Eol}',	Shortest string "\n"
return (int)Tokens.Eol;
            break;
        case 13: // Recognized '{equal}',	Shortest string "="
return (int)Tokens.equal;
            break;
        case 14: // Recognized '{minus}',	Shortest string "-"
return (int)Tokens.minus;
            break;
        case 15: // Recognized '{Ident}',	Shortest string "P"
        case 16: // Recognized '{Ident}',	Shortest string "R"
        case 17: // Recognized '{Ident}',	Shortest string "I"
        case 18: // Recognized '{Ident}',	Shortest string "S"
        case 19: // Recognized '{Ident}',	Shortest string "F"
        case 20: // Recognized '{Ident}',	Shortest string "C"
        case 21: // Recognized '{Ident}',	Shortest string "B"
        case 22: // Recognized '{Ident}',	Shortest string "D"
        case 23: // Recognized '{Ident}',	Shortest string "L"
        case 24: // Recognized '{Ident}',	Shortest string "V"
        case 25: // Recognized '{Ident}',	Shortest string "M"
        case 29: // Recognized '{Ident}',	Shortest string "MA"
        case 30: // Recognized '{Ident}',	Shortest string "MAI"
        case 32: // Recognized '{Ident}',	Shortest string "VA"
        case 33: // Recognized '{Ident}',	Shortest string "VAR"
        case 34: // Recognized '{Ident}',	Shortest string "VARI"
        case 35: // Recognized '{Ident}',	Shortest string "VARIA"
        case 36: // Recognized '{Ident}',	Shortest string "VARIAB"
        case 37: // Recognized '{Ident}',	Shortest string "VARIABL"
        case 38: // Recognized '{Ident}',	Shortest string "VARIABLE"
        case 40: // Recognized '{Ident}',	Shortest string "LI"
        case 41: // Recognized '{Ident}',	Shortest string "LO"
        case 42: // Recognized '{Ident}',	Shortest string "LOC"
        case 43: // Recognized '{Ident}',	Shortest string "LOCA"
        case 45: // Recognized '{Ident}',	Shortest string "LIN"
        case 47: // Recognized '{Ident}',	Shortest string "DE"
        case 48: // Recognized '{Ident}',	Shortest string "DEB"
        case 50: // Recognized '{Ident}',	Shortest string "DEBU"
        case 51: // Recognized '{Ident}',	Shortest string "DEBUG"
        case 52: // Recognized '{Ident}',	Shortest string "DEBUGG"
        case 53: // Recognized '{Ident}',	Shortest string "DEBUGGE"
        case 55: // Recognized '{Ident}',	Shortest string "BR"
        case 56: // Recognized '{Ident}',	Shortest string "BA"
        case 57: // Recognized '{Ident}',	Shortest string "BAC"
        case 58: // Recognized '{Ident}',	Shortest string "BACK"
        case 59: // Recognized '{Ident}',	Shortest string "BACKT"
        case 60: // Recognized '{Ident}',	Shortest string "BACKTR"
        case 61: // Recognized '{Ident}',	Shortest string "BACKTRA"
        case 62: // Recognized '{Ident}',	Shortest string "BACKTRAC"
        case 64: // Recognized '{Ident}',	Shortest string "BRI"
        case 65: // Recognized '{Ident}',	Shortest string "BRIG"
        case 66: // Recognized '{Ident}',	Shortest string "BRIGH"
        case 67: // Recognized '{Ident}',	Shortest string "BRIGHT"
        case 68: // Recognized '{Ident}',	Shortest string "BRIGHTS"
        case 69: // Recognized '{Ident}',	Shortest string "BRIGHTSC"
        case 70: // Recognized '{Ident}',	Shortest string "BRIGHTSCR"
        case 71: // Recognized '{Ident}',	Shortest string "BRIGHTSCRI"
        case 72: // Recognized '{Ident}',	Shortest string "BRIGHTSCRIP"
        case 74: // Recognized '{Ident}',	Shortest string "CO"
        case 75: // Recognized '{Ident}',	Shortest string "CU"
        case 76: // Recognized '{Ident}',	Shortest string "CUR"
        case 77: // Recognized '{Ident}',	Shortest string "CURR"
        case 78: // Recognized '{Ident}',	Shortest string "CURRE"
        case 79: // Recognized '{Ident}',	Shortest string "CURREN"
        case 81: // Recognized '{Ident}',	Shortest string "COM"
        case 82: // Recognized '{Ident}',	Shortest string "COMP"
        case 83: // Recognized '{Ident}',	Shortest string "COMPI"
        case 84: // Recognized '{Ident}',	Shortest string "COMPIL"
        case 85: // Recognized '{Ident}',	Shortest string "COMPILI"
        case 86: // Recognized '{Ident}',	Shortest string "COMPILIN"
        case 88: // Recognized '{Ident}',	Shortest string "FI"
        case 89: // Recognized '{Ident}',	Shortest string "FU"
        case 90: // Recognized '{Ident}',	Shortest string "FUN"
        case 91: // Recognized '{Ident}',	Shortest string "FUNC"
        case 92: // Recognized '{Ident}',	Shortest string "FUNCT"
        case 93: // Recognized '{Ident}',	Shortest string "FUNCTI"
        case 94: // Recognized '{Ident}',	Shortest string "FUNCTIO"
        case 96: // Recognized '{Ident}',	Shortest string "FIL"
        case 98: // Recognized '{Ident}',	Shortest string "ST"
        case 99: // Recognized '{Ident}',	Shortest string "STO"
        case 101: // Recognized '{Ident}',	Shortest string "RU"
        case 102: // Recognized '{Ident}',	Shortest string "RUN"
        case 103: // Recognized '{Ident}',	Shortest string "RUNN"
        case 104: // Recognized '{Ident}',	Shortest string "RUNNI"
        case 105: // Recognized '{Ident}',	Shortest string "RUNNIN"
        case 107: // Recognized '{Ident}',	Shortest string "PR"
        case 108: // Recognized '{Ident}',	Shortest string "PRI"
        case 109: // Recognized '{Ident}',	Shortest string "PRIN"
return (int)Tokens.dgIdent;
            break;
        case 26: // Recognized '{Number}',	Shortest string "0"
        case 28: // Recognized '{Number}',	Shortest string ".0"
return (int)Tokens.dgNumber;
            break;
        case 27: // Recognized '{Str}',	Shortest string "''"
return (int)Tokens.dgStr;
            break;
        case 31: // Recognized '{dgMain}',	Shortest string "MAIN"
return (int)Tokens.dgMain;
            break;
        case 39: // Recognized '{dgVariables}',	Shortest string "VARIABLES"
return (int)Tokens.dgVariables;
            break;
        case 44: // Recognized '{dgLocal}',	Shortest string "LOCAL"
return (int)Tokens.dgLocal;
            break;
        case 46: // Recognized '{dgLine}',	Shortest string "LINE"
return (int)Tokens.dgLine;
            break;
        case 49: // Recognized '{dgDev}',	Shortest string "DEV"
return (int)Tokens.dgDev;
            break;
        case 54: // Recognized '{dgDebugger}',	Shortest string "DEBUGGER"
return (int)Tokens.dgDebugger;
            break;
        case 63: // Recognized '{dgBacktrace}',	Shortest string "BACKTRACE"
return (int)Tokens.dgBacktrace;
            break;
        case 73: // Recognized '{dgBS}',	Shortest string "BRIGHTSCRIPT"
return (int)Tokens.dgBS;
            break;
        case 80: // Recognized '{dgCurrent}',	Shortest string "CURRENT"
return (int)Tokens.dgCurrent;
            break;
        case 87: // Recognized '{dgCompiling}',	Shortest string "COMPILING"
return (int)Tokens.dgCompiling;
            break;
        case 95: // Recognized '{dgFunction}',	Shortest string "FUNCTION"
return (int)Tokens.dgFunction;
            break;
        case 97: // Recognized '{dgFile}',	Shortest string "FILE"
return (int)Tokens.dgFile;
            break;
        case 100: // Recognized '{dgStop}',	Shortest string "STOP"
return (int)Tokens.dgStop;
            break;
        case 106: // Recognized '{dgRunning}',	Shortest string "RUNNING"
return (int)Tokens.dgRunning;
            break;
        case 110: // Recognized '{print}',	Shortest string "PRINT"
return (int)Tokens.print;
            break;
        case 111: // Recognized '{dgMinus}',	Shortest string "------"
return (int)Tokens.dgMinus;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
