// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.0.0.0
// Machine:  CELSO-PC
// DateTime: 12/05/2016 22:12:36
// UserName: Celso
// Input file <SpecFiles\BrightScript.y - 12/05/2016 22:12:29>

// options: babel lines diagnose & report gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using BrightScriptTools.Gppg.GPGen;
using System.Collections;
using BrightScriptTools.GPlex;
using BrightScriptTools.GPlex.Parser;

namespace BrightScriptTools.Compiler
{
public enum Tokens {error=2,EOF=3,bar=4,dot=5,semi=6,
    star=7,lt=8,gt=9,ltEqual=10,gtEqual=11,notEqual=12,
    comma=13,slash=14,lBrac=15,rBrac=16,lPar=17,rPar=18,
    lBrace=19,rBrace=20,Eol=21,equal=22,plus=23,minus=24,
    questionMark=25,colon=26,bsIdent=27,bsNumber=28,bsStr=29,bsCmnt=30,
    bsFuncs=31,bsType=32,bsAs=33,bsTrue=34,bsFalse=35,bsInvalid=36,
    bsNot=37,bsM=38,bsStop=39,bsReturn=40,bsPrint=41,bsIf=42,
    bsElse=43,bsFor=44,bsTo=45,bsEach=46,bsStep=47,bsIn=48,
    bsWhile=49,bsSub=50,bsFunction=51,bsEnd=52,maxParseToken=53,EOL=54,
    comment=55,errTok=56,repErr=57};

// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.0.0.0")]
public abstract class ScanBase : AbstractScanner<int,LexSpan> {
  private LexSpan __yylloc = new LexSpan();
  public override LexSpan yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }

  protected abstract int CurrentSc { get; set; }
  //
  // Override the virtual EolState property if the scanner state is more
  // complicated then a simple copy of the current start state ordinal
  //
  public virtual int EolState { get { return CurrentSc; } set { CurrentSc = value; } }
}

// Interface class for 'colorizing' scanners
public interface IColorScan {
  void SetSource(string source, int offset);
  int GetNext(ref int state, out int start, out int end);
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.0.0.0")]
public class ScanObj {
  public int token;
  public int yylval;
  public LexSpan yylloc;
  public ScanObj( int t, int val, LexSpan loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.0.0.0")]
public partial class Parser: ShiftReduceParser<int, LexSpan>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[87];
  private static State[] states = new State[167];
  private static string[] nonTerms = new string[] {
      "Program", "$accept", "SourceElements", "EolOpt", "SourceElement", "SubDeclaration", 
      "FunctionDeclaration", "ParameterList", "Type", "StatementList", "Parameter", 
      "ParameterTail", "Literal", "Statement", "AssignStatement", "IfStatement", 
      "IterationStatement", "ReturnStatement", "DebuggerStatement", "PrintStatement", 
      "SequenceExpression", "SingleExpression", "Block", "UnaryExpression", "CallExpression", 
      "BinaryExpression", "MemberExpression", "LabelledStatementList", "LabelledStatement", 
      "LabelledStatementTail", "LabelSeparator", "FunctionStatement", "Arguments", 
      "MathOperator", "BooleanOperator", "NullLiteral", "BooleanLiteral", "StringLiteral", 
      "NumericLiteral", };

  static Parser() {
    states[0] = new State(new int[]{21,8,50,-18,51,-18,3,-18},new int[]{-1,1,-3,3,-4,5});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{3,4});
    states[4] = new State(-2);
    states[5] = new State(new int[]{50,11,51,158,3,-4},new int[]{-5,6,-6,10,-7,157});
    states[6] = new State(new int[]{21,8,50,-18,51,-18,3,-18},new int[]{-3,7,-4,5});
    states[7] = new State(-3);
    states[8] = new State(new int[]{21,8,50,-18,51,-18,3,-18,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18,43,-18,20,-18},new int[]{-4,9});
    states[9] = new State(-17);
    states[10] = new State(-5);
    states[11] = new State(new int[]{27,12});
    states[12] = new State(new int[]{17,13});
    states[13] = new State(new int[]{27,110,18,-10},new int[]{-8,14,-11,105});
    states[14] = new State(new int[]{18,15});
    states[15] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,16,-4,19});
    states[16] = new State(new int[]{52,17});
    states[17] = new State(new int[]{50,18});
    states[18] = new State(-8);
    states[19] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81,42,116,44,126,49,141,40,147,39,151,41,153,25,155,52,-20,43,-20},new int[]{-14,20,-15,22,-21,23,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80,-16,115,-17,125,-18,146,-19,150,-20,152});
    states[20] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18,43,-18},new int[]{-10,21,-4,19});
    states[21] = new State(-19);
    states[22] = new State(-21);
    states[23] = new State(new int[]{22,24,21,-27,19,-27,17,-27,24,-27,37,-27,27,-27,31,-27,36,-27,34,-27,35,-27,29,-27,28,-27,42,-27,44,-27,49,-27,40,-27,39,-27,41,-27,25,-27,52,-27,43,-27});
    states[24] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,25,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[25] = new State(-28);
    states[26] = new State(new int[]{5,27,22,-39,21,-39,19,-39,17,-39,24,-39,37,-39,27,-39,31,-39,36,-39,34,-39,35,-39,29,-39,28,-39,42,-39,44,-39,49,-39,40,-39,39,-39,41,-39,25,-39,52,-39,43,-39,45,-39,13,-39,20,-39,18,-39});
    states[27] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,28,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[28] = new State(-40);
    states[29] = new State(-41);
    states[30] = new State(new int[]{21,8,27,-18,20,-18},new int[]{-28,31,-4,33});
    states[31] = new State(new int[]{20,32});
    states[32] = new State(-47);
    states[33] = new State(new int[]{27,43,20,-49},new int[]{-29,34});
    states[34] = new State(new int[]{21,39,13,41,20,-18},new int[]{-30,35,-31,36,-4,42});
    states[35] = new State(-48);
    states[36] = new State(new int[]{27,43},new int[]{-29,37});
    states[37] = new State(new int[]{21,39,13,41,20,-18},new int[]{-30,38,-31,36,-4,42});
    states[38] = new State(-50);
    states[39] = new State(new int[]{21,8,27,-18,20,-18},new int[]{-4,40});
    states[40] = new State(new int[]{27,-55,20,-17});
    states[41] = new State(-56);
    states[42] = new State(-51);
    states[43] = new State(new int[]{26,44});
    states[44] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81,51,95},new int[]{-21,45,-32,46,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[45] = new State(-52);
    states[46] = new State(-53);
    states[47] = new State(-42);
    states[48] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,49,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[49] = new State(new int[]{18,50});
    states[50] = new State(-62);
    states[51] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-22,52,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[52] = new State(-63);
    states[53] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-22,54,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[54] = new State(-64);
    states[55] = new State(-43);
    states[56] = new State(new int[]{17,57,23,86,24,87,7,88,14,89,8,90,10,91,9,92,11,93,22,94,5,-46,21,-46,19,-46,37,-46,27,-46,31,-46,36,-46,34,-46,35,-46,29,-46,28,-46,42,-46,44,-46,49,-46,40,-46,39,-46,41,-46,25,-46,52,-46,43,-46,45,-46,13,-46,20,-46,18,-46,16,-46},new int[]{-34,82,-35,84});
    states[57] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81,18,-61},new int[]{-33,58,-21,60,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[58] = new State(new int[]{18,59});
    states[59] = new State(-57);
    states[60] = new State(new int[]{13,61,18,-59});
    states[61] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81,18,-61},new int[]{-33,62,-21,60,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[62] = new State(-60);
    states[63] = new State(new int[]{15,64,17,-67,23,-67,24,-67,7,-67,14,-67,8,-67,10,-67,9,-67,11,-67,22,-67,5,-67,21,-67,19,-67,37,-67,27,-67,31,-67,36,-67,34,-67,35,-67,29,-67,28,-67,42,-67,44,-67,49,-67,40,-67,39,-67,41,-67,25,-67,52,-67,43,-67,45,-67,13,-67,20,-67,18,-67,16,-67});
    states[64] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-22,65,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[65] = new State(new int[]{16,66});
    states[66] = new State(-68);
    states[67] = new State(new int[]{17,68});
    states[68] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81,18,-61},new int[]{-33,69,-21,60,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[69] = new State(new int[]{18,70});
    states[70] = new State(-58);
    states[71] = new State(-44);
    states[72] = new State(-45);
    states[73] = new State(-78);
    states[74] = new State(-82);
    states[75] = new State(-79);
    states[76] = new State(-83);
    states[77] = new State(-84);
    states[78] = new State(-80);
    states[79] = new State(-85);
    states[80] = new State(-81);
    states[81] = new State(-86);
    states[82] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-22,83,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[83] = new State(-65);
    states[84] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-22,85,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[85] = new State(-66);
    states[86] = new State(-69);
    states[87] = new State(-70);
    states[88] = new State(-71);
    states[89] = new State(-72);
    states[90] = new State(-73);
    states[91] = new State(-74);
    states[92] = new State(-75);
    states[93] = new State(-76);
    states[94] = new State(-77);
    states[95] = new State(new int[]{17,96});
    states[96] = new State(new int[]{27,110,18,-10},new int[]{-8,97,-11,105});
    states[97] = new State(new int[]{18,98});
    states[98] = new State(new int[]{33,103,21,-16,52,-16,19,-16,17,-16,24,-16,37,-16,27,-16,31,-16,36,-16,34,-16,35,-16,29,-16,28,-16,42,-16,44,-16,49,-16,40,-16,39,-16,41,-16,25,-16},new int[]{-9,99});
    states[99] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,100,-4,19});
    states[100] = new State(new int[]{52,101});
    states[101] = new State(new int[]{51,102});
    states[102] = new State(-54);
    states[103] = new State(new int[]{32,104});
    states[104] = new State(-15);
    states[105] = new State(new int[]{13,107,18,-12},new int[]{-12,106});
    states[106] = new State(-9);
    states[107] = new State(new int[]{27,110},new int[]{-11,108});
    states[108] = new State(new int[]{13,107,18,-12},new int[]{-12,109});
    states[109] = new State(-11);
    states[110] = new State(new int[]{22,111,33,103,13,-16,18,-16},new int[]{-9,114});
    states[111] = new State(new int[]{36,74,34,76,35,77,29,79,28,81},new int[]{-13,112,-36,73,-37,75,-38,78,-39,80});
    states[112] = new State(new int[]{33,103,13,-16,18,-16},new int[]{-9,113});
    states[113] = new State(-13);
    states[114] = new State(-14);
    states[115] = new State(-22);
    states[116] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,117,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[117] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18,43,-18},new int[]{-10,118,-4,19});
    states[118] = new State(new int[]{52,119,43,121});
    states[119] = new State(new int[]{42,120});
    states[120] = new State(-29);
    states[121] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,122,-4,19});
    states[122] = new State(new int[]{52,123});
    states[123] = new State(new int[]{42,124});
    states[124] = new State(-30);
    states[125] = new State(-23);
    states[126] = new State(new int[]{46,133,19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-15,127,-21,140,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[127] = new State(new int[]{45,128});
    states[128] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,129,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[129] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,130,-4,19});
    states[130] = new State(new int[]{52,131});
    states[131] = new State(new int[]{44,132});
    states[132] = new State(-31);
    states[133] = new State(new int[]{27,134});
    states[134] = new State(new int[]{48,135});
    states[135] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,136,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[136] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,137,-4,19});
    states[137] = new State(new int[]{52,138});
    states[138] = new State(new int[]{44,139});
    states[139] = new State(-32);
    states[140] = new State(new int[]{22,24});
    states[141] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,142,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[142] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,143,-4,19});
    states[143] = new State(new int[]{52,144});
    states[144] = new State(new int[]{49,145});
    states[145] = new State(-33);
    states[146] = new State(-24);
    states[147] = new State(new int[]{21,149,19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,148,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[148] = new State(-34);
    states[149] = new State(-35);
    states[150] = new State(-25);
    states[151] = new State(-36);
    states[152] = new State(-26);
    states[153] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,154,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[154] = new State(-37);
    states[155] = new State(new int[]{19,30,17,48,24,51,37,53,27,63,31,67,36,74,34,76,35,77,29,79,28,81},new int[]{-21,156,-22,26,-23,29,-24,47,-25,55,-27,56,-26,71,-13,72,-36,73,-37,75,-38,78,-39,80});
    states[156] = new State(-38);
    states[157] = new State(-6);
    states[158] = new State(new int[]{27,159});
    states[159] = new State(new int[]{17,160});
    states[160] = new State(new int[]{27,110,18,-10},new int[]{-8,161,-11,105});
    states[161] = new State(new int[]{18,162});
    states[162] = new State(new int[]{33,103,21,-16,52,-16,19,-16,17,-16,24,-16,37,-16,27,-16,31,-16,36,-16,34,-16,35,-16,29,-16,28,-16,42,-16,44,-16,49,-16,40,-16,39,-16,41,-16,25,-16},new int[]{-9,163});
    states[163] = new State(new int[]{21,8,19,-18,17,-18,24,-18,37,-18,27,-18,31,-18,36,-18,34,-18,35,-18,29,-18,28,-18,42,-18,44,-18,49,-18,40,-18,39,-18,41,-18,25,-18,52,-18},new int[]{-10,164,-4,19});
    states[164] = new State(new int[]{52,165});
    states[165] = new State(new int[]{51,166});
    states[166] = new State(-7);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3,3});
    rules[3] = new Rule(-3, new int[]{-4,-5,-3});
    rules[4] = new Rule(-3, new int[]{-4});
    rules[5] = new Rule(-5, new int[]{-6});
    rules[6] = new Rule(-5, new int[]{-7});
    rules[7] = new Rule(-7, new int[]{51,27,17,-8,18,-9,-10,52,51});
    rules[8] = new Rule(-6, new int[]{50,27,17,-8,18,-10,52,50});
    rules[9] = new Rule(-8, new int[]{-11,-12});
    rules[10] = new Rule(-8, new int[]{});
    rules[11] = new Rule(-12, new int[]{13,-11,-12});
    rules[12] = new Rule(-12, new int[]{});
    rules[13] = new Rule(-11, new int[]{27,22,-13,-9});
    rules[14] = new Rule(-11, new int[]{27,-9});
    rules[15] = new Rule(-9, new int[]{33,32});
    rules[16] = new Rule(-9, new int[]{});
    rules[17] = new Rule(-4, new int[]{21,-4});
    rules[18] = new Rule(-4, new int[]{});
    rules[19] = new Rule(-10, new int[]{-4,-14,-10});
    rules[20] = new Rule(-10, new int[]{-4});
    rules[21] = new Rule(-14, new int[]{-15});
    rules[22] = new Rule(-14, new int[]{-16});
    rules[23] = new Rule(-14, new int[]{-17});
    rules[24] = new Rule(-14, new int[]{-18});
    rules[25] = new Rule(-14, new int[]{-19});
    rules[26] = new Rule(-14, new int[]{-20});
    rules[27] = new Rule(-14, new int[]{-21});
    rules[28] = new Rule(-15, new int[]{-21,22,-21});
    rules[29] = new Rule(-16, new int[]{42,-21,-10,52,42});
    rules[30] = new Rule(-16, new int[]{42,-21,-10,43,-10,52,42});
    rules[31] = new Rule(-17, new int[]{44,-15,45,-21,-10,52,44});
    rules[32] = new Rule(-17, new int[]{44,46,27,48,-21,-10,52,44});
    rules[33] = new Rule(-17, new int[]{49,-21,-10,52,49});
    rules[34] = new Rule(-18, new int[]{40,-21});
    rules[35] = new Rule(-18, new int[]{40,21});
    rules[36] = new Rule(-19, new int[]{39});
    rules[37] = new Rule(-20, new int[]{41,-21});
    rules[38] = new Rule(-20, new int[]{25,-21});
    rules[39] = new Rule(-21, new int[]{-22});
    rules[40] = new Rule(-21, new int[]{-22,5,-21});
    rules[41] = new Rule(-22, new int[]{-23});
    rules[42] = new Rule(-22, new int[]{-24});
    rules[43] = new Rule(-22, new int[]{-25});
    rules[44] = new Rule(-22, new int[]{-26});
    rules[45] = new Rule(-22, new int[]{-13});
    rules[46] = new Rule(-22, new int[]{-27});
    rules[47] = new Rule(-23, new int[]{19,-28,20});
    rules[48] = new Rule(-28, new int[]{-4,-29,-30});
    rules[49] = new Rule(-28, new int[]{-4});
    rules[50] = new Rule(-30, new int[]{-31,-29,-30});
    rules[51] = new Rule(-30, new int[]{-4});
    rules[52] = new Rule(-29, new int[]{27,26,-21});
    rules[53] = new Rule(-29, new int[]{27,26,-32});
    rules[54] = new Rule(-32, new int[]{51,17,-8,18,-9,-10,52,51});
    rules[55] = new Rule(-31, new int[]{21,-4});
    rules[56] = new Rule(-31, new int[]{13});
    rules[57] = new Rule(-25, new int[]{-27,17,-33,18});
    rules[58] = new Rule(-25, new int[]{31,17,-33,18});
    rules[59] = new Rule(-33, new int[]{-21});
    rules[60] = new Rule(-33, new int[]{-21,13,-33});
    rules[61] = new Rule(-33, new int[]{});
    rules[62] = new Rule(-24, new int[]{17,-21,18});
    rules[63] = new Rule(-24, new int[]{24,-22});
    rules[64] = new Rule(-24, new int[]{37,-22});
    rules[65] = new Rule(-26, new int[]{-27,-34,-22});
    rules[66] = new Rule(-26, new int[]{-27,-35,-22});
    rules[67] = new Rule(-27, new int[]{27});
    rules[68] = new Rule(-27, new int[]{27,15,-22,16});
    rules[69] = new Rule(-34, new int[]{23});
    rules[70] = new Rule(-34, new int[]{24});
    rules[71] = new Rule(-34, new int[]{7});
    rules[72] = new Rule(-34, new int[]{14});
    rules[73] = new Rule(-35, new int[]{8});
    rules[74] = new Rule(-35, new int[]{10});
    rules[75] = new Rule(-35, new int[]{9});
    rules[76] = new Rule(-35, new int[]{11});
    rules[77] = new Rule(-35, new int[]{22});
    rules[78] = new Rule(-13, new int[]{-36});
    rules[79] = new Rule(-13, new int[]{-37});
    rules[80] = new Rule(-13, new int[]{-38});
    rules[81] = new Rule(-13, new int[]{-39});
    rules[82] = new Rule(-36, new int[]{36});
    rules[83] = new Rule(-37, new int[]{34});
    rules[84] = new Rule(-37, new int[]{35});
    rules[85] = new Rule(-38, new int[]{29});
    rules[86] = new Rule(-39, new int[]{28});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 227 "SpecFiles\BrightScript.y"
 #line default
}
}
